server.port=${PORT:8080}

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# URL de ton site Render
app.base-url=${APP_BASE_URL:http://localhost:${PORT:8080}}

# dossier temporaire pour stocker les fichiers
app.storage-dir=/tmp/doc-converter
