server.port=${PORT:8080}

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# URL de ton site Railway
app.base-url=https://doc-converter-project-production.up.railway.app

# dossier temporaire pour stocker les fichiers
app.storage-dir=/tmp/doc-converter
